Config
CodeUtilities/CodeUtilities-2.0 pull request #104
Opened 2021-12-20 18:35 UTC by TechStreetDev

2021-12-20 19:19 UTC, Vatten commented on common/src/main/java/io/github/codeutilities/scripts/ScriptHandler.java
> +    public static void init() {
why?

2021-12-20 19:42 UTC, TechStreetDev commented on common/src/main/java/io/github/codeutilities/scripts/ScriptHandler.java
> +    public static void init() {
I did this to match all others in CodeUtilities.java

2021-12-22 12:23 UTC, Reasonlesss requested changes, later dismissed

2021-12-22 12:23 UTC, Reasonlesss commented on common/src/main/java/io/github/codeutilities/config/impl/MiscellaneousGroup.java
> +        ConfigSubGroup projectaudio = new ConfigSubGroup("projectaudio");
project audio?

2021-12-22 12:23 UTC, Reasonlesss commented on common/src/main/java/io/github/codeutilities/config/internal/settings/OverlayVisibility.java
> +        return "projectaudio_overlay_visability";
????

2021-12-22 12:29 UTC, TechStreetDev commented on common/src/main/java/io/github/codeutilities/config/impl/MiscellaneousGroup.java
> +        ConfigSubGroup projectaudio = new ConfigSubGroup("projectaudio");
its used as a example i had nothing else to register to show an example

2022-01-15 11:14 UTC, Reasonlesss approved these changes

2022-01-16 17:15 UTC, tk2217 approved these changes

2022-02-06 07:10 UTC, merged