Plot History
CodeUtilities/CodeUtilities-2.0 pull request #153
Opened 2022-03-06 14:11 UTC by CheaterTim

was suggested in #152
sorry for my bad code. but it works :>
![boolean](https://cdn.discordapp.com/attachments/604764182830645259/947410584746491954/what_does_a_boolean_mean.gif)

2022-03-07 08:20 UTC, TechStreetDev requested changes, later dismissed

2022-03-07 08:20 UTC, TechStreetDev commented on src/main/java/io/github/codeutilities/mod/commands/CommandHandler.java
> +           new HistoryCommand()
Why is this not inline with the other commands? It’s visually annoying

2022-03-07 08:20 UTC, TechStreetDev commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/HistoryCommand.java
> +                            new LiteralText("\n§r §r §r §r §r §r §r §r §r §r §r §r ").append(
I believe we are moving away from § codes as they are depreciated.

2022-03-07 08:20 UTC, TechStreetDev commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/HistoryCommand.java
> +                        ChatUtil.sendMessage(new LiteralText("§cYou need to enable §lplot history§c in the settings to use this command."), null);
More § codes

2022-03-07 08:20 UTC, TechStreetDev commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/HistoryCommand.java
> +                        ChatUtil.sendMessage(new LiteralText("§cno plots in the history."), null);
More § codes

2022-03-07 08:20 UTC, TechStreetDev commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/HistoryCommand.java
> +                                                                new LiteralText("§7Click to join!")
More § codes

2022-03-07 12:29 UTC, CheaterTim commented
alr will fix those

2022-03-10 23:54 UTC, tk2217 requested changes

2022-03-10 23:54 UTC, tk2217 commented on src/main/java/io/github/codeutilities/mod/PlotHistoryRecorder.java
> +        File file = new File(FILE_PATH);
For files it's probably best to use `Path`. Also, you should probably use the fabric loader api to get the game dir because the working dir might not be the game dir with custom launchers.
https://maven.fabricmc.net/docs/fabric-loader-0.13.3/net/fabricmc/loader/api/FabricLoader.html#getGameDir()

2022-03-10 23:54 UTC, tk2217 commented on src/main/java/io/github/codeutilities/mod/PlotHistoryRecorder.java
> +            BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH));
Here you can use `Files.writeString`

2022-03-11 00:43 UTC, CheaterTim commented on src/main/java/io/github/codeutilities/mod/PlotHistoryRecorder.java
> +            BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH));
that method is java 11+ tho? won't that break in some environments where something below 11 is used?

2022-03-11 00:44 UTC, CheaterTim commented on src/main/java/io/github/codeutilities/mod/PlotHistoryRecorder.java
> +            BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH));
and also its more consistent with the Buffered IO I used for reading the file

2022-03-12 07:27 UTC, TechStreetDev commented on src/main/java/io/github/codeutilities/mod/PlotHistoryRecorder.java
> +            BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH));
This wont matter due to using it in other places in the project

2022-03-12 11:49 UTC, CheaterTim commented on src/main/java/io/github/codeutilities/mod/PlotHistoryRecorder.java
> +            BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH));
maybe I misunderstood this but there are 0 matches for `Files.writeString`
![image](https://user-images.githubusercontent.com/85891155/158016791-d88d6091-5bad-489e-ae2c-636644ba2a7f.png)

2022-03-12 19:20 UTC, Reasonlesss commented on src/main/java/io/github/codeutilities/mod/PlotHistoryRecorder.java
> +            BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH));
Tech was referring to java 11

2022-03-12 19:32 UTC, CheaterTim commented on src/main/java/io/github/codeutilities/mod/PlotHistoryRecorder.java
> +            BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH));
alr will change it

2022-04-10 21:44 UTC, CheaterTim commented
so... will this be merged or not?

2022-04-11 02:49 UTC, 8Blits commented
> 

If it's bad code then why do a pull request.

2022-04-11 09:15 UTC, CheaterTim commented
........

2022-04-12 17:39 UTC, 8Blits commented
At line 13 why did you make the file a ".sff"?

2022-04-14 20:05 UTC, CheaterTim commented
> At line 13 of [PlotHistoryRecorder.java](https://github.com/CodeUtilities/CodeUtilities/pull/153/commits/56618a4cf71b1187f34c2d66889f64cc98433dec#diff-476a30ce6ffdf6db85386e9a621c756663d372add3523fcbcd743378cb0090fb) why did you make the file a ".sff"?

**s**tupid **f**ile **f**ormat

2022-04-18 14:43 UTC, closed without merging

2022-04-18 17:11 UTC, 8Blits commented
why didn't you just do .txt lmao