Audio Support
CodeUtilities/CodeUtilities-2.0 pull request #42
Opened 2021-04-27 18:46 UTC by Tomoli75

Adds P:A support to CodeUtils, with a customisable backend URL.
Volume is customisable via changing the Noteblock / Jukebox sound level, or the master sound level.

2021-04-27 19:19 UTC, Reasonlesss commented on src/main/java/io/github/codeutilities/audio/AudioHandler.java
> +                        .setQuery("username="+username+"&source="+("forge-"+CodeUtilities.MOD_ID+"-"+CodeUtilities.MOD_VERSION))
CodeUtilities is a fabric mod :)

2021-04-27 19:20 UTC, Reasonlesss commented on src/main/java/io/github/codeutilities/config/ModConfig.java
> +    @ConfigEntry.BoundedDiscrete(min = 0, max = 100000)
BoundedDiscrete is for numbers

2021-04-27 19:23 UTC, Reasonlesss commented
Please also make this feature a toggle.

2021-04-27 19:28 UTC, Tomoli75 reviewed
Still attempting to get YouTube support working in Java, currently not functional

2021-04-27 20:46 UTC, Tomoli75 commented
Should now be all working! Ready for review

2021-04-27 21:10 UTC, RyanLandDev commented
super cool. Reasonless is weak so he's sleeping rn but he'll review tomorrow i guess

2021-04-28 02:33 UTC, Owen1212055 requested changes
Please try to clear this large diff on the Lang file.

2021-04-28 02:35 UTC, Owen1212055 requested changes

2021-04-28 02:35 UTC, Owen1212055 commented on src/main/java/io/github/codeutilities/audio/AudioHandler.java
> +                    executor.scheduleAtFixedRate(handleVolume, 0, 1, TimeUnit.SECONDS);
Store the executor on a private static final field.

2021-04-29 16:09 UTC, Owen1212055 approved these changes
It's fine

2021-05-02 11:11 UTC, merged