AwesomeSoundLib
CodeUtilities/CodeUtilities-2.0 pull request #77
Opened 2021-08-20 14:46 UTC by SirObby

AwesomeSoundLib support.

Added:
- SoundDownloader
- SoundPlayer
- Consent System
- MessageChecker
- Commands for Consent.
- Configs

2021-08-20 14:47 UTC, SirObby commented
RyanLand knows what this PR is about.

2021-08-20 15:41 UTC, SirObby commented
Alright it should finally have corrected awemanager and awefile to AweManager and AweFile

2021-08-20 17:29 UTC, RyanLandDev requested changes
I feel very mean when posting this, but please don't take it as that. Here's a bunch of requested changes which should be done before merging.

2021-08-20 17:29 UTC, ryandev2 commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/AweslibCommand.java
> +        if(!AweManager.DownloadPhase) {
Variables are named `likeThis`

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/AweslibCommand.java
> +public class AweslibCommand extends Command {
Wouldnt "AWESLibCommand" and "AWEManager" make more sense?

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/AweslibCommand.java
> +        if(Objects.equals(action, "allow")) {
Replace with action.equals("allow")

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/AweslibCommand.java
> +            ChatUtil.sendMessage("< aweslib > You have decided to allow this domain.");
Use a constant for the `< aweslib >` prefix. And maybe make a private static method which sends a message with this prefix.

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/AweslibCommand.java
> +                .then(ArgBuilder.argument("action", StringArgumentType.greedyString())
Make the available actions possible to autocomplete

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/MessageType.java
> +    JOIN_DF,// SirObby's garbage Project: Audio - SirObby_
This comment isnt necessary; perhaps rename the sound to something like `AWE_SOUND`

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/checks/SoundEffectCheck.java
> +        // Hide spies (Session spy, Muted spy, DM spy)
This comment isnt supposed to be here...

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/checks/SoundEffectCheck.java
> +        return stripped.contains("(AWESLIB SYSTEM MESSAGE)");
Shouldnt this be String#startsWith?

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/finalizers/SoundEffectFinalizer.java
> +            message.typeIs(MessageType.SOUND_EFFECT);
??? what is the point of this?
Shouldn't this be in an if statement?
Currently every message will run this code

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/finalizers/SoundEffectFinalizer.java
> +            if(stripped.contains("(AWESLIB SYSTEM MESSAGE)")) {
The MessageCheck already takes care of this, that's what the `Message#typeIs` is for

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/finalizers/SoundEffectFinalizer.java
> +                if(AweManager.Token.equals("empty")) {
Refer to a previous comment aswell, variables are named `likeThis`

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/finalizers/SoundEffectFinalizer.java
> +                        CodeUtilities.log("Set token to " + tok);
In the log this is of no use. Should be something like "Set AWE token to..."

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/finalizers/SoundEffectFinalizer.java
> +                    //SoundPlayer.playSnd(sound);
Should be named `playSound` instead

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/mixin/message/MMessageListener.java
> +            AweManager.plotChange();
Use the StateChangeEvent instead.

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweFile.java
> +public class AweFile {
Should probably be named `AWEFile`

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweFile.java
> +        java.io.File fileOne = pathOne.toFile();
Import the File class so you can just do File instead of java.io.File

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweFile.java
> +        Path pathOne = FabricLoader.getInstance().getGameDir().resolve("CodeUtilities").resolve(fileFolder);
Doesn't need two resolve calls, can be simplified to use CodeUtilities/ + fileFolder

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweFile.java
> +    public static void createFolder(String fileFolder) {
This method should be in the FileUtil class.

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweFile.java
> +    public static void cleanFolder(String fileFolder) {
This method should be in the FileUtil class.

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweFile.java
> +    public static long bytesToMeg(long bytes) {
Should also be in FileUtil

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweFile.java
> +    public static long getFolderSize(File dir) {
Move to FileUtil

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweFile.java
> +                System.out.println(file.getName() + " " + file.length());
This systemout can be removed

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +    public static String AWEDATABASE = Config.getString("awesdb");
This will make the setting only update on restart. Do you want that?

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +    public static ArrayList<String> sounds = new ArrayList<String>();
Second <String> can be simplified to <>, and it should prob be List<String> at the start instead

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +    public static ArrayList<String> consented = new ArrayList<String>();
Same as last comment

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +    public AweManager() {
Empty constructor, so unnecessary

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +            Thread doStuff = new Thread(() -> {
You don't have to set a variable if it's not necessary; can simply be new Thread `...`

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +                //String sendJson = "{ \"name\": \"Baeldung\", \"java\": true }";
Commented out code can be removed if no longer necessary

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +                                    e.printStackTrace();
Shouldn't there be some kind of error handling instead of only printing the stack trace?

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +            doStuff.start();
Refer to earlier thread comment; the .start() can be appended to the thread constructor

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +        String[] Splitted = toParse.split(",");
vars are `likeThis`

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +        ArrayList<String> toConsented = new ArrayList<String>(Arrays.asList(Splitted));
Same as last list comment

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +        CodeUtilities.log(String.valueOf(maxMb));
Do all of these need to be logged?

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundDownloader.java
> +    public static File download(String URL, String ToLocation) {
Move to FileUtil

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundDownloader.java
> +        Path dir = FabricLoader.getInstance().getGameDir().resolve("CodeUtilities").resolve("aweslib");
Instead of two appended resolve calls simplify to "CodeUtilities/aweslib"

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundDownloader.java
> +            ChatUtil.sendMessage("< aweslib > The plot "+ AweManager.plotID + " reaches the maxMb limit of " + AweManager.maxMb);
Use String#format

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundDownloader.java
> +        java.io.File[] fileAmount = dir.toFile().listFiles();
Import the File class.

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundDownloader.java
> +            String name = sound.replace("/", "").replace(":", "").replace(".", "") + ".wav";
Use regex, and shouldn't it use replaceAll?

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundPlayer.java
> +    /*public static void mp3ToWav(File mp3Data, String name) throws UnsupportedAudioFileException, IOException {
Remove commented out code

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundPlayer.java
> +        name = name.replace("/", "").replace(":", "").replace(".", "") + ".wav";
Use a method; this is the same code as before

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundPlayer.java
> +    public static void playSnd(String name) throws LineUnavailableException {
Rename to playSound

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundPlayer.java
> +        Path pathOne = FabricLoader.getInstance().getGameDir().resolve("CodeUtilities").resolve("aweslib").resolve(name);
Simplify to "CodeUtilities/aweslib/" + name

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundPlayer.java
> +            e.printStackTrace();
Please handle the errors instead of only printing the stack trace.

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundPlayer.java
> +            gainControl.setValue(gainControl.getMaximum() * 1);
* 1? what is the use of that?

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/resources/assets/codeutilities/lang/en_us.json
> +    "config.codeutilities.option.maxAmnt.tooltip": "Maximum Amount of sounds a plot can use for sounds.",
Lowercase amount

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/resources/assets/codeutilities/lang/en_us.json
> +    "config.codeutilities.option.maxMB.tooltip": "Maximum Megabytes a plot can use for sounds.",
Lowercase megabytes

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/resources/assets/codeutilities/lang/en_us.json
> +    "config.codeutilities.option.awesdb.tooltip": "The URL AwesomeSoundLib will connect to, to validate Plots.",
Lowercase Plots

2021-08-20 17:29 UTC, RyanLandDev commented on src/main/resources/resources/assets/codeutilities/lang/en_us.json
> +{
Duplicate file ?

2021-08-20 17:41 UTC, SirObby commented
Will look into these changes soon.

2021-08-20 18:10 UTC, SirObby commented on src/main/resources/resources/assets/codeutilities/lang/en_us.json
> +{
Fixed

2021-08-20 18:10 UTC, SirObby commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundDownloader.java
> +    public static File download(String URL, String ToLocation) {
Do you want me to move the entire SoundDownloader code to FileUtil?

2021-08-20 18:10 UTC, SirObby commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +        CodeUtilities.log(String.valueOf(maxMb));
No, this was for debugging purpose, will remove.

2021-08-20 18:10 UTC, SirObby commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +        String[] Splitted = toParse.split(",");
?

2021-08-20 18:11 UTC, SirObby commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/AweslibCommand.java
> +public class AweslibCommand extends Command {
You want me to change the names of the classes to AWESLibCommand and AWEManager?

2021-08-20 18:11 UTC, SirObby commented
> I feel very mean when posting this, but please don't take it as that. Here's a bunch of requested changes which should be done before merging.

Trying to get all these done before I go to sleep :D

2021-08-20 18:21 UTC, SirObby commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundPlayer.java
> +            gainControl.setValue(gainControl.getMaximum() * 1);
This is some code from stackoverflow I believe that does something.

2021-08-20 18:30 UTC, SirObby commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/checks/SoundEffectCheck.java
> +        return stripped.contains("(AWESLIB SYSTEM MESSAGE)");
If it has stripped the color then yes.

2021-08-20 18:37 UTC, SirObby commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/finalizers/SoundEffectFinalizer.java
> +            message.typeIs(MessageType.SOUND_EFFECT);
Apparently not read your request below.

2021-08-20 18:44 UTC, tk2217 requested changes

2021-08-20 18:44 UTC, tk2217 commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/MessageType.java
> +    AWE_SOUND,
Shouldn't this be something like `AWE_MESSAGE`

2021-08-20 18:44 UTC, tk2217 commented on src/main/java/io/github/codeutilities/sys/aweslib/AweUtils.java
> +    public static void sendMessage(String Message) {
Couldn't you just use `ChatUtil.sendMessage` instead of this. (If it's absolutely necessary just add a new ChatType.)

2021-08-20 18:49 UTC, SirObby commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +    public static ArrayList<String> sounds = new ArrayList<String>();
I will continue with ArrayLists as using a List would probably have little-to-no difference.

2021-08-20 18:54 UTC, tk2217 commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +    public static ArrayList<String> sounds = new ArrayList<String>();
Its really a cleanliness of code thing to have the variable type be `List`, also ryan was talking about how you have the type in the `<>` when constructing the object.
It could instead be:
```java
public static List<String> sounds = new ArrayList<>(); 
```

2021-08-20 19:01 UTC, SirObby commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +    public static String AWEDATABASE = Config.getString("awesdb");
See the Init function below.
Also this is the same for all the settings, will need to be changed!

2021-08-20 23:23 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/AweslibCommand.java
> +public class AweslibCommand extends Command {
Yes, I think this capitalization would make more sense.

2021-08-20 23:23 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/checks/SoundEffectCheck.java
> +        return stripped.contains("(AWESLIB SYSTEM MESSAGE)");
The variable is called `stripped` for a reason lol, yes, that string is without the color.

2021-08-20 23:24 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +    public static String AWEDATABASE = Config.getString("awesdb");
alright 👍

2021-08-20 23:25 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +        String[] Splitted = toParse.split(",");
All variables should be named in `thisCaseType`. In this case, you are using `Stripped`, not starting with an uncapitalized letter.

2021-08-20 23:25 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/AweManager.java
> +        CodeUtilities.log(String.valueOf(maxMb));
👍

2021-08-20 23:26 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundDownloader.java
> +    public static File download(String URL, String ToLocation) {
No, just this `download` method; since its universal and not exclusive to sounds as far as I'm aware

2021-08-20 23:26 UTC, RyanLandDev commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundPlayer.java
> +            gainControl.setValue(gainControl.getMaximum() * 1);
Well last time I checked multiplying a number by 1 doesn't do anything

2021-08-20 23:28 UTC, tk2217 commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/AweslibCommand.java
> +    public LiteralArgumentBuilder<FabricClientCommandSource> subcommand(MinecraftClient mc, LiteralArgumentBuilder<FabricClientCommandSource> literal) {
these could probably just be put in register, this really just complicates things, if you wanted to you could extract the code that is run on execute into separate methods
```java
    void registerCommand() {
        dispatcher.register(CommandManager.literal("foo")
            .executes(this::execute)); // This refers to the "execute" method below.
    }
     
    private int execute(CommandContext<Object> context) {
        return 0;
    }
```

2021-08-20 23:29 UTC, tk2217 commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/MessageType.java
> +    AWE_SOUND,
or `AWE_SYSTEM_MESSAGE` (would probably be more descriptive)

2021-08-21 04:53 UTC, SirObby commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundPlayer.java
> +            gainControl.setValue(gainControl.getMaximum() * 1);
Well from what I know Its probably there for a reason.

2021-08-21 04:55 UTC, SirObby commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/AweslibCommand.java
> +    public LiteralArgumentBuilder<FabricClientCommandSource> subcommand(MinecraftClient mc, LiteralArgumentBuilder<FabricClientCommandSource> literal) {
I did not understand the command handler that well when trying to add the options,
but I don't think I should separate the aweslib command into 3.

2021-08-21 04:58 UTC, SirObby commented on src/main/java/io/github/codeutilities/sys/aweslib/AweUtils.java
> +    public static void sendMessage(String Message) {
Pretty sure Ryan requested I make AWEUtils since I'm using a prefix or smth.

2021-08-21 05:03 UTC, SirObby commented
Alright so the only things missing I think is making the command work.
Enabling and Disabling.
And hopefully making maxMB and maxAmnt a bit more restrictive.

2021-08-21 05:07 UTC, SirObby commented on src/main/java/io/github/codeutilities/mod/features/social/chat/message/checks/SoundEffectCheck.java
> +        return stripped.contains("(AWESLIB SYSTEM MESSAGE)");
I will try it.

2021-08-21 06:26 UTC, SirObby commented
Everything except making maxMB and maxAmnt is done and working.
The PR is mergeable now I think.

2021-08-21 11:51 UTC, General-Mudkip commented on src/main/java/io/github/codeutilities/sys/aweslib/AWEUtils.java
> +    private static String prefix = "< aweslib > ";
Should probably be a constant.

2021-08-21 11:58 UTC, SirObby commented on src/main/java/io/github/codeutilities/sys/aweslib/AWEUtils.java
> +    private static String prefix = "< aweslib > ";
I'll add that later, but at the moment it seems like this is not going to be merged.

2021-08-21 12:01 UTC, SirObby commented on src/main/java/io/github/codeutilities/sys/aweslib/AWEUtils.java
> +    private static String prefix = "< aweslib > ";
Wait you aren't a CU dev or a contributor! You're an impostor!
(But that is a good idea.)

2021-08-21 12:14 UTC, General-Mudkip commented on src/main/java/io/github/codeutilities/sys/aweslib/AWEUtils.java
> +    private static String prefix = "< aweslib > ";
It's just a change from `private static String prefix = "< aweslib > ";` to `private static final String PREFIX = "< aweslib >;`

2021-08-21 12:46 UTC, SirObby commented on src/main/java/io/github/codeutilities/sys/aweslib/AWEUtils.java
> +    private static String prefix = "< aweslib > ";
Yeah I know lol.

2021-08-21 21:19 UTC, tk2217 requested changes

2021-08-21 21:19 UTC, tk2217 commented on src/main/java/io/github/codeutilities/mod/commands/impl/other/AWESLibCommand.java
> +    private int run(CommandContext<FabricClientCommandSource> ctx) {
More descriptive names for these would be nice.

2021-08-21 21:19 UTC, tk2217 commented on src/main/java/io/github/codeutilities/sys/aweslib/AWEFile.java
> +public class AWEFile {
This should be removed as it is not being used.

2021-08-21 21:19 UTC, tk2217 commented on src/main/java/io/github/codeutilities/sys/aweslib/SoundDownloader.java
> +            File sFile = FileUtil.download(sound, loc);
Couldn't you have it so the request is limited to under the remaining value in bytes and then when a file is downloaded subtract its size from the from the remaining amount of bytes you have.

2021-08-22 15:26 UTC, tk2217 commented
We have unfortunately decided to deny your pull request due to it not fitting with the goals of the CodeUilities project at this time.

2021-08-22 15:26 UTC, closed without merging

2021-08-23 12:11 UTC, SirObby commented
Because LooserRIP said something about aweslib in a hidden channel?