script changes
CodeUtilities/CodeUtilities-2.0 pull request #97
Opened 2021-12-14 10:39 UTC by BlazeMCworld

2021-12-14 19:03 UTC, TechStreetDev approved these changes, later dismissed

2021-12-14 19:04 UTC, RedCommand-dev submitted a review, later dismissed
mongus :D

2021-12-16 19:50 UTC, Reasonlesss requested changes, later dismissed

2021-12-16 19:50 UTC, Reasonlesss commented on common/src/main/java/io/github/codeutilities/util/ComponentUtil.java
> +    public static String toFormattedString(Component message) {
Why?

2021-12-16 19:56 UTC, BlazeMCworld commented on common/src/main/java/io/github/codeutilities/util/ComponentUtil.java
> +    public static String toFormattedString(Component message) {
![image](https://user-images.githubusercontent.com/62186782/146440472-04dacdec-4bc7-4021-afc9-38c106081cb6.png)
because its used here?

2021-12-19 14:10 UTC, Reasonlesss commented
This pull request is a bit too volatile imo.

2021-12-19 14:48 UTC, TechStreetDev approved these changes, later dismissed
Looks good!

2021-12-20 13:50 UTC, Reasonlesss requested changes

2021-12-20 13:50 UTC, Reasonlesss commented on common/src/main/java/io/github/codeutilities/CodeUtilities.java
> +    public static final JsonParser JSON_PARSER = new JsonParser();
is this mc built in?

2021-12-20 13:50 UTC, Reasonlesss commented on common/src/main/java/io/github/codeutilities/menu/ScriptEditorMenu.java
> +        errorMsg = new CText( 75, 105, "§aValid", 0, 1, true, true);
§ codes are legacy tmk

2021-12-20 13:50 UTC, BlazeMCworld commented on common/src/main/java/io/github/codeutilities/CodeUtilities.java
> +    public static final JsonParser JSON_PARSER = new JsonParser();
gson

2021-12-20 13:51 UTC, BlazeMCworld commented on common/src/main/java/io/github/codeutilities/menu/ScriptEditorMenu.java
> +        errorMsg = new CText( 75, 105, "§aValid", 0, 1, true, true);
ik but i still like them, if you want you can replace them

2021-12-20 13:51 UTC, Reasonlesss commented on common/src/main/java/io/github/codeutilities/CodeUtilities.java
> +    public static final JsonParser JSON_PARSER = new JsonParser();
i mean like is this gson provided by mc?

2021-12-20 13:51 UTC, BlazeMCworld commented on common/src/main/java/io/github/codeutilities/CodeUtilities.java
> +    public static final JsonParser JSON_PARSER = new JsonParser();
i didnt add any dependencies so i think so

2021-12-20 13:52 UTC, Reasonlesss commented on common/src/main/java/io/github/codeutilities/CodeUtilities.java
> +    public static final JsonParser JSON_PARSER = new JsonParser();
alright just making sure

2021-12-20 13:52 UTC, Reasonlesss commented on common/src/main/java/io/github/codeutilities/menu/ScriptEditorMenu.java
> +        errorMsg = new CText( 75, 105, "§aValid", 0, 1, true, true);
I do not want to use the legacy stuff

2021-12-20 13:55 UTC, TechStreetDev commented on common/src/main/java/io/github/codeutilities/menu/ScriptEditorMenu.java
> +        errorMsg = new CText( 75, 105, "§aValid", 0, 1, true, true);
Its awkward to use other stuff

2021-12-20 13:56 UTC, Reasonlesss commented on common/src/main/java/io/github/codeutilities/menu/ScriptEditorMenu.java
> +        errorMsg = new CText( 75, 105, "§aValid", 0, 1, true, true);
Legacy is a big no, I will stand by this.

2021-12-20 13:57 UTC, TechStreetDev commented on common/src/main/java/io/github/codeutilities/menu/ScriptEditorMenu.java
> +        errorMsg = new CText( 75, 105, "§aValid", 0, 1, true, true);
What other options do we have?

2021-12-20 13:57 UTC, Reasonlesss commented on common/src/main/java/io/github/codeutilities/menu/ScriptEditorMenu.java
> +        errorMsg = new CText( 75, 105, "§aValid", 0, 1, true, true);
Components, actually rendering colored text the intended way.

2021-12-20 14:20 UTC, TechStreetDev commented on common/src/main/java/io/github/codeutilities/menu/ScriptEditorMenu.java
> +        errorMsg = new CText( 75, 105, "§aValid", 0, 1, true, true);
Also there not legacy in architectury @Reasonlesss it readds them and adds §x codes

2021-12-20 17:44 UTC, Reasonlesss approved these changes

2021-12-20 17:54 UTC, TechStreetDev approved these changes

2021-12-20 18:06 UTC, merged